<?php 
class TranslateJsonFeed {
	
	public static $dataBinding_news = array(
		// "@context"  => "http://schema.org",
		// "version" 	=> "https://jsonfeed.org/version/1",
		// "title" 	=> "Communecter's JSON Feed",
		// "@type"		=> "News",
		"id" 		=> array("valueOf"  => '_id.$id', 
							 "type" 	=> "url", 
							 "prefix"   => "/#news.detail.id.",
							 "suffix"   => ""),
		"url" 		=> array("valueOf"  => '_id.$id', 
						 "type" 	=> "url", 
						 "prefix"   => "/#news.detail.id.",
						 "suffix"   => ""),
	    "name" 		=> array("valueOf" => "name"),
	  	"url"		=> array("valueOf" => "url"),
	  	"title" 	=> array("valueOf" => "text"),
	  	"content_html" => array("valueOf" => "text"),
	  	"date_published" => array("valueOf" => "date",
							  	  "type" => "date",
								  "prefix"   => "",
								  "suffix"   => ""),
	);

	public static $dataBinding_allOrganization = array(
		"id" 		=> array("valueOf"  => '_id.$id', 
							 "type" 	=> "url", 
							 "prefix"   => "/#page.type.organizations.id.",
							 "suffix"   => ""),
		"url" 		=> array("valueOf"  => '_id.$id', 
						 "type" 	=> "url", 
						 "prefix"   => "/#page.type.organizations.id.",
						 "suffix"   => ""),
	    "title" 		=> array("valueOf" => "name"),
	    "author" => array ("valueOf" => "author"),
	    "date_last_modified" => array("valueOf" => "modified",
							  	  "type" => "date",
								  "prefix"   => "",
								  "suffix"   => ""),
	    "author" 	=> array("valueOf" => "creator",
	    					 "type" => "url",
	    	 				 "prefix"   => "/#page.type.citoyens.id.",
						 	 "suffix"   => ".viewer."),
	  	"url"		=> array("valueOf" => "url"),
	  	// "title" 	=> array("valueOf" => "text"),
	  	// "content_html" => array("valueOf" => "text"),
	  	"content"	=> array( "shortDescription" => array("valueOf" => "shortDescription"),
	  						  "Description" => array("valueOf" => "Description"),
	  						 ),
	);

	public static $dataBinding_allEvent  = array(

		"id" 		=> array("valueOf"  => '_id.$id', 
							 "type" 	=> "url", 
							 "prefix"   => "/#page.type.organizations.id.",
							 "suffix"   => ""),
		"url" 		=> array("valueOf"  => '_id.$id', 
						 "type" 	=> "url", 
						 "prefix"   => "/#page.type.organizations.id.",
						 "suffix"   => ""),
	    "title" 		=> array("valueOf" => "name"),
	    "author" => array ("valueOf" => "author"),
	    "dates" => array ( "startDate" => array("valueOf" => "startDate",
							  	  "type" => "date",
								  "prefix"   => "",
								  "suffix"   => ""),
	    					"endDate" => array("valueOf" => "endDate",
							  	  "type" => "date",
								  "prefix"   => "",
								  "suffix"   => ""),
	    					"lastModifiedDate" => array("valueOf" => "modified",
							  	  "type" => "date",
								  "prefix"   => "",
								  "suffix"   => ""),
	    				),
	    "author" 	=> array("valueOf" => "creator",
	    					 "type" => "url",
	    	 				 "prefix"   => "/#page.type.citoyens.id.",
						 	 "suffix"   => ".viewer."),
	  	"url"		=> array("valueOf" => "url"),
	  	// "title" 	=> array("valueOf" => "text"),
	  	// "content_html" => array("valueOf" => "text"),
	  	"content"	=> array( "shortDescription" => array("valueOf" => "shortDescription"),
	  						  "Description" => array("valueOf" => "Description"),
	  						 ),

		
		);

	public static $dataBinding_allProject  = array(


		"id" 		=> array("valueOf"  => '_id.$id', 
							 "type" 	=> "url", 
							 "prefix"   => "/#page.type.organizations.id.",
							 "suffix"   => ""),
		"url" 		=> array("valueOf"  => '_id.$id', 
						 "type" 	=> "url", 
						 "prefix"   => "/#page.type.organizations.id.",
						 "suffix"   => ""),
	    "title" 		=> array("valueOf" => "name"),
	    "lastModifiedDate" => array("valueOf" => "modified",
								  	 "type" => "date",
									 "prefix"   => "",
									 "suffix"   => ""),
	    "author" 	=> array("valueOf" => "creator",
	    					 "type" => "url",
	    	 				 "prefix"   => "/#page.type.citoyens.id.",
						 	 "suffix"   => ".viewer."),
	  	"url"		=> array("valueOf" => "url"),
	  	// "title" 	=> array("valueOf" => "text"),
	  	// "content_html" => array("valueOf" => "text"),
	  	"content"	=> array( "shortDescription" => array("valueOf" => "shortDescription"),
	  						  "Description" => array("valueOf" => "Description"),
	  						 ),
	);

	public static $dataBinding_allPerson = array(

		"id" 		=> array("valueOf"  => '_id.$id', 
							 "type" 	=> "url", 
							 "prefix"   => "/#page.type.organizations.id.",
							 "suffix"   => ""),
		"url" 		=> array("valueOf"  => '_id.$id', 
						 "type" 	=> "url", 
						 "prefix"   => "/#page.type.organizations.id.",
						 "suffix"   => ""),
	    "title" 		=> array("valueOf" => "name"),
	    "lastModifiedDate" => array("valueOf" => "modified",
								  	 "type" => "date",
									 "prefix"   => "",
									 "suffix"   => ""),
	  	"url"		=> array("valueOf" => "url"),
	  	// "title" 	=> array("valueOf" => "text"),
	  	// "content_html" => array("valueOf" => "text"),
	  	"content"	=> array( "shortDescription" => array("valueOf" => "shortDescription"),
	  						  "Description" => array("valueOf" => "Description"),
	  						 ),
	);

	public static $dataBinding_city = array(

		"id" 		=> array("valueOf"  => '_id.$id', 
							 "type" 	=> "url", 
							 "prefix"   => "/#page.type.organizations.id.",
							 "suffix"   => ""),
		"url" 		=> array("valueOf"  => '_id.$id', 
						 "type" 	=> "url", 
						 "prefix"   => "/#page.type.organizations.id.",
						 "suffix"   => ""),
	    "title" 		=> array("valueOf" => "alternateName"),
	    "author" => array ("valueOf" => "author"),
	    "date_last_modified" => array("valueOf" => "modified",
							  	  "type" => "date",
								  "prefix"   => "",
								  "suffix"   => ""),
	    "author" 	=> array("valueOf" => "creator",
	    					 "type" => "url",
	    	 				 "prefix"   => "/#page.type.citoyens.id.",
						 	 "suffix"   => ".viewer."),
	  	"url"		=> array("valueOf" => "url"),
	  	// "title" 	=> array("valueOf" => "text"),
	  	// "content_html" => array("valueOf" => "text"),
	  	"content"	=> array( "shortDescription" => array("valueOf" => "shortDescription"),
	  						  "Description" => array("valueOf" => "Description"),
	);
}